# Configuration for pre-commit hooks (see https://pre-commit.com/).
# Eventually, the hooks described here will be run as tests before merging each PR.

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.13
    hooks:
      - id: uv-lock


  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff-check
        types_or: [python, pyi]
      - id: ruff-format


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        files: '(bot)/.*\.py$'
        args: [--config-file=./pyproject.toml]
        additional_dependencies:
          - pydantic-settings
          - pytelegrambotapi


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files
        exclude: ^(.*\/dummy.*|.*\.json)$
        args: [ "--maxkb=750", "--enforce-all" ]
      - id: detect-private-key
      - id: check-merge-conflict


  - repo: local
    hooks:
      - id: pytest
        name: run pytest
        entry: pytest --doctest-modules --tb=short
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

      - id: print_actual_packages
        name: print_actual_packages
        entry: uv tree --outdated --depth=1 --color=always
        language: system
        pass_filenames: false
        verbose: true
